"""Add GIN indexes for JSONB fields

Revision ID: c8be560f57e6
Revises: e523a8cb8020
Create Date: 2026-04-29 16:29:22.983197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8be560f57e6'
down_revision: Union[str, Sequence[str], None] = 'e523a8cb8020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_result_measurements_gin', 'result', ['measurements'], unique=False, postgresql_using='gin')
    op.create_index('ix_sample_geometry_gin', 'sample', ['geometry'], unique=False, postgresql_using='gin')
    op.create_index('ix_sample_phys_props_gin', 'sample', ['physical_properties'], unique=False, postgresql_using='gin')
    op.create_index('ix_striker_geom_dims_gin', 'striker', ['geometric_dimensions'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_striker_geom_dims_gin', table_name='striker', postgresql_using='gin')
    op.drop_index('ix_sample_phys_props_gin', table_name='sample', postgresql_using='gin')
    op.drop_index('ix_sample_geometry_gin', table_name='sample', postgresql_using='gin')
    op.drop_index('ix_result_measurements_gin', table_name='result', postgresql_using='gin')
    # ### end Alembic commands ###
