"""Initial schema

Revision ID: e523a8cb8020
Revises: 
Create Date: 2026-04-29 16:28:13.034668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e523a8cb8020'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'contract', 'customer', ['id_customer'], ['id_customer'])
    op.drop_constraint(op.f('experiment_support_rod_id_fkey'), 'experiment', type_='foreignkey')
    op.drop_constraint(op.f('experiment_id_contract_fkey'), 'experiment', type_='foreignkey')
    op.drop_constraint(op.f('experiment_loading_rod_id_fkey'), 'experiment', type_='foreignkey')
    op.drop_constraint(op.f('experiment_id_sample_fkey'), 'experiment', type_='foreignkey')
    op.drop_constraint(op.f('experiment_id_status_fkey'), 'experiment', type_='foreignkey')
    op.drop_constraint(op.f('experiment_experiment_type_code_fkey'), 'experiment', type_='foreignkey')
    op.drop_constraint(op.f('experiment_id_striker_fkey'), 'experiment', type_='foreignkey')
    op.create_foreign_key(None, 'experiment', 'experiment_status', ['id_status'], ['id_status'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'experiment', 'measuring_rod', ['support_rod_id'], ['id_rod'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'experiment', 'experiment_type', ['experiment_type_code'], ['experiment_type_code'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'experiment', 'contract', ['id_contract'], ['id_contract'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'experiment', 'striker', ['id_striker'], ['id_striker'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'experiment', 'sample', ['id_sample'], ['id_sample'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'experiment', 'measuring_rod', ['loading_rod_id'], ['id_rod'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'experiment', type_='foreignkey')
    op.drop_constraint(None, 'experiment', type_='foreignkey')
    op.drop_constraint(None, 'experiment', type_='foreignkey')
    op.drop_constraint(None, 'experiment', type_='foreignkey')
    op.drop_constraint(None, 'experiment', type_='foreignkey')
    op.drop_constraint(None, 'experiment', type_='foreignkey')
    op.drop_constraint(None, 'experiment', type_='foreignkey')
    op.create_foreign_key(op.f('experiment_id_striker_fkey'), 'experiment', 'striker', ['id_striker'], ['id_striker'])
    op.create_foreign_key(op.f('experiment_experiment_type_code_fkey'), 'experiment', 'experiment_type', ['experiment_type_code'], ['experiment_type_code'])
    op.create_foreign_key(op.f('experiment_id_status_fkey'), 'experiment', 'experiment_status', ['id_status'], ['id_status'])
    op.create_foreign_key(op.f('experiment_id_sample_fkey'), 'experiment', 'sample', ['id_sample'], ['id_sample'])
    op.create_foreign_key(op.f('experiment_loading_rod_id_fkey'), 'experiment', 'measuring_rod', ['loading_rod_id'], ['id_rod'])
    op.create_foreign_key(op.f('experiment_id_contract_fkey'), 'experiment', 'contract', ['id_contract'], ['id_contract'])
    op.create_foreign_key(op.f('experiment_support_rod_id_fkey'), 'experiment', 'measuring_rod', ['support_rod_id'], ['id_rod'])
    op.drop_constraint(None, 'contract', type_='foreignkey')
    # ### end Alembic commands ###
